### PR TITLE
Fixed compilation error on Visual Studio 2013

### PR DESCRIPTION
**Pull request by Ogritor**
We are happy of the new framework you developed, so we tested for you on Visual Studio (seems you don't have Win7/Win8)
and fixed the only compilation bug we found). We are overall happy of the new design, looking for a quick first release.

### CODE REVIEW

**Comment by xxxJhon** [comment]
Is is possible that both Visual Studio and GCC accept implicit size for arrays?

I.E:

priv::TypeInfoP types[] // do not specity size here.
-                        { &typeid(typename SmartPointers::type)... };

I'm asking because I think imposing a fixed size just for visual studio may bloat the executable more than needed. don't have cmake so can't test it myself right now

**Comment by Darelbi** [comment]
I don't have Visual Studio, could you check that for me (you just need to add all files to a new project/solution), there's no particular linking step or configuration, files should compile "stand-alone".
@Ogritor can you check that for me too? thanks.

**Comment by xxxJhon** [comment]
It won't compile, sorry. But you can use a global array I think so it will have a fixed size (100?).

**Comment by Darelbi** [comment]
that's going to be thread unsafe. I could use thread local storage maybe. But at least on GCC having a fixed size array do not bloat the binary size (few KB of difference for ~60 bindings)

**Pull request merged**
